[project]
name = "closet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Garrett Mooney", email = "garrettrmooney@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "polars>=1.32.0",
    "rich>=13.7.1",
    "srsly>=2.4.8",
    "yt-dlp>=2024.7.25",
]

[project.scripts]
update-playlist = "closet.playlist:main"
report = "closet.report:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
