name: Data Pipeline

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main

jobs:
  data-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --locked

      - name: Run data pipeline
        run: uv run update-playlist
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Generate report
        run: uv run report

      - name: Conditional commit and push
        run: uv run scripts/conditional_commit.py

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pipeline-log
          path: data/log.html
